pipeline {

  agent any 

  stages {

    stage('Build') {
      steps {
        // Checkout code from Git repo
        checkout scm  

        // Print current working directory
        sh "pwd"

        // Build Docker image in the TIC directory
        sh "docker build -t radiagulzan/ticketlogging:latest -f TIC/Dockerfile ."
      }
    }

    stage('Deploy') {
       steps {
        sh 'docker rm -f new-ticketlogging-container'
        sh 'docker run -p 5000:5000 --name new-ticketlogging-container radiagulzan/ticketlogging:latest &'

       }
    }

  }

}