pipeline {
  agent any
  stages {
    stage('setup') {
      steps {
        sh "apt-get install python3-venv -y"
        sh "apt-get install python3-pip -y"
        sh "python3 -m venv venv"
        sh ". venv/bin/activate"
        sh "pip3 install -r requirements.txt"
      }
    }
  }
}
